### ISSUE TITLE
cljs support

### ISSUE THREAD

**Issue by baskeboler** [roboli/flato#4]
migrating to cljc appears to be pretty simple.
Integer/parseInt and regex functions need to be extracted to new functions that handle the js and java differences.

**Comment by roboli** [comment]
Thanks for feedback @baskeboler. I'll try to get this done in the next few weeks.

**Comment by roboli** [comment]
Apologies for delay @baskeboler, this now done [d2ab2bc](https://github.com/roboli/balloon/commit/d2ab2bc0f4e6a59d8d61e17acf71d98976d7c6f1)

**Comment by baskeboler** [comment]
awesome!
